# Site settings
title: CV - Agustin Bergia Baragiotta
description: Agustin Bergia Baragiotta - Resume
# baseurl: "" # the subpath of your site, e.g. /blog
#url: "192.168.0.56:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Agustin Bergia Baragiotta
user_description: Con 7 años de experiencia en desarrollo ETL, he desempeñado mi carrera en la industria bancaria, enfocándome en migraciones y desarrollo de Data Warehouses para bancos internacionales. 
user_title: ETL Developer SR.
email: agustin.bergia@gmail.com
# twitter_username: lorem_ipsum
#instagram_username: lorem_ipsum
#facebook_username: lorem_ipsum.urraco
linkedin_username: agustin-bergia-baragiotta-06371282
github_username:  agustinbergia
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

